### ISSUE TITLE
thanks what replaces slot ?

### ISSUE THREAD

**Issue by adamprocter** [wobsoriano/vue3-swatches#1]
I have been upgrading a project to Vue3 and so having this appear is great as I used swatches before so thank you. 

Can you advise as slot attributes are now deprecated what should I do here ? for slot="trigger"
What has this been changed to ? thanks again

<VSwatches
          v-model="color"
          @input="chooseColor(nodes.node_id, color)"
          :swatches="swatches"
          :shapes="shapes"
          show-border
          show-fallback
          fallback-input-type="color"
        >
          <button @click.prevent slot="trigger"></button>
        </VSwatches>

**Comment by wobsoriano** [comment]
Can you try this instead?

```html
<VueSwatches v-model="color">
  <template v-slot:trigger>
    <button @click.prevent>{{ color }}</button>
  </template>
</VueSwatches>
```

**Comment by adamprocter** [comment]
thanks have edited 

 <VSwatches
          v-model="nodes.node_color"
          @input="chooseColor(e)"
          :swatches="swatches"
          :shapes="shapes"
          show-border
          show-fallback
          fallback-input-type="color"
        >
          <template v-slot:trigger>
            <button @click.prevent>{{ nodes.node_color }}</button>
          </template>
        </VSwatches>

which seems to be working to some degree but it is still not triggering the method chooseColor when I change the colour in the picker

**Comment by wobsoriano** [comment]
I think you don't need the chooseColor anymore? Since you have `v-model` already. How about watching the value instead?

```ts
watchEffect(() => {
  // do something with nodes.value.node_colors
})
```

**Comment by adamprocter** [comment]
I need the choose color to make a change to the database... I have split it a bit more I can only assume the trigger is not working like before...here is the full component FYI https://gitlab.adamprocter.co.uk/nn/nodenoggin-vue3/-/blob/main/src/components/MyNodes.vue  

I will look at the watch thing

**Comment by wobsoriano** [comment]
Okay, I think you're looking for this

```html
<VueSwatches v-model="color" @update:modelValue="chooseColor($event)" />
```

https://v3.vuejs.org/guide/migration/v-model.html#_3-x-syntax

**Comment by adamprocter** [comment]
perfect thank you :) this works now  here is my final code for completeness.

```
     <VSwatches
          v-model="nodes.node_color"
          :swatches="swatches"
          :shapes="shapes"
          @update:modelValue="chooseColor(nodes.node_id, nodes.node_color)"
          show-border
          show-fallback
          fallback-input-type="color"
        >
          <template v-slot:trigger>
            <button @click.prevent>{{ nodes.node_color }}</button>
          </template>
        </VSwatches>

```

and the method

```

    chooseColor(nodeid, color) {
      this.$store.dispatch('colorNode', { nodeid, color })
      setTimeout(this.loadData, 500)
    },

```
