### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by kawoki** [wobsoriano/vue3-swatches#3]
I am getting error of `Object(...) is not a function` on vue3-swatches.esm.js. I've just recently installed this component.

Here's the error
![image](https://user-images.githubusercontent.com/12818739/137592130-724c6867-7fa0-4d84-b25d-27b78bd1ca55.png)

Here's another error where it occurs
![image](https://user-images.githubusercontent.com/12818739/137592308-2de17f47-7bde-4d36-923a-79b9b57c77f1.png)

And here's my code
```vue
<template>
   <VSwatches v-model="color" show-fallback fallback-input-type="color" popover-x="left"></VSwatches>
</template>

<script>
import VSwatches from 'vue3-swatches'
import { ref } from 'vue'

export default {
  setup() {
    const color = ref("#1FBC9C")

    return { color }
  }
}
</script>
```

Thanks in advance

**Comment by wobsoriano** [comment]
Need a basic repro https://codesandbox.io/
