### ISSUE TITLE
Fix export types

### ISSUE THREAD

**Issue by leje512** [wobsoriano/vue3-swatches#7]
Hi, we're currently doing a migration from Vue 2 and Vue 3 and used this package to replace the old vue-swatches. Thanks for your work!

There was an error with typescript, that the types are not correctly exported. 

 ``` There are types at '.../node_modules/vue3-swatches/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue3-swatches' library may need to update its package.json or typings.ts(7016) ```
 
We fixed it with patch-package and had to add ``"types": "./dist/types/index.d.ts",``to the default export after line 13 in the package.json. The package.json looks like this after patching:

```
{
  "name": "vue3-swatches",
  "version": "1.2.3",
  "description": "🎨 Vue 3 swatch picker",
  "keywords": [
    "vue",
    "swatch"
  ],
  "main": "dist/vue3-swatches.cjs.js",
  "module": "dist/vue3-swatches.es.js",
  "types": "./dist/types/index.d.ts",
  "exports": {
    ".": {
+++   "types": "./dist/types/index.d.ts",
      "require": "./dist/vue3-swatches.cjs.js",
      "import": "./dist/vue3-swatches.es.js"
    },
    "./nuxt": {
      "import": "./nuxt/module.mjs"
    },
    "./dist/style.css": "./dist/style.css"
  },
  "files": [
    "dist",
    "nuxt"
  ],
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.2.0",
    "bumpp": "^7.1.1",
    "rimraf": "^3.0.2",
    "typescript": "^4.8.4",
    "vite": "^3.2.3",
    "vue": "^3.2.45",
    "vue-tsc": "^1.0.9"
  },
  "peerDependencies": {
    "vue": "^3.2.0"
  },
  "engines": {
    "node": ">=16"
  },
  "scripts": {
    "build": "rimraf dist && vue-tsc && vite build",
    "release": "bumpp --commit --push --tag && pnpm publish"
  }
}
```

Nuxt users probably have the same problem, but I didn't try that. Would be great if you could fix this problem, then we could remove the patch again. Thanks!:)

**Comment by TheFlyer1983** [comment]
Yes, I am getting this issue on a Nuxt 3 project.

**Comment by wobsoriano** [comment]
Fixed in https://github.com/wobsoriano/vue3-swatches/commit/50e3b393a53bd95a02c57e5df044954c4acbef41
